name: pilkawe12-cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to cloud server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git clone https://github.com/ibrahimsyah-tkpd/pilkawe12
            cd ~/pilkawe12
            git pull origin main
            docker-compose down --remove-orphans
	          docker-compose up --build -d